name: BuildRelease

on:
  push:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Increment version
      run: |
        echo ::set-env name=TAG_NAME::$(cat ./VERSION)
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.3

    - name: Install dependencies
      run: |
        if [ -f ./builder/requirements.txt ]; then pip3 install -r ./builder/requirements.txt; fi
        
    - name: Create config script
      env:
        gitPass: ${{ secrets.SLX_GIT_PASS }}
        gitToken: ${{ secrets.SLX_GIT_TOKEN }}
        gitUser: ${{ secrets.SLX_GIT_USER }}
      run: | 
        echo -e "version = 'v${{ env.TAG_NAME }}'\ngithub_username = '$gitUser'\ngithub_password = '$gitPass'\ngitlab_private_access_token = '$gitToken'"> ./builder/config.py
    
    - name: Compile DeepSea Zip
      run: |
        cd ./builder
        python ./builder.py deepsea output="./deepsea.zip"

    - name: Compile DeepSea-patches Zip
      run: |
        cd ./builder
        python ./builder.py deepsea-patches output="./deepsea-patched.zip"
    
    - name: Compile DeepSea-minimal Zip
      run: |
        cd ./builder
        python ./builder.py deepsea-mini output="./deepsea-minimal.zip"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: true
          prerelease: false


    - name: Upload Release Asset - DeepSea
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./builder/deepsea.zip
          asset_name: deepsea_v${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip


    - name: Upload Release Asset - DeepSea-Patches
      id: upload-release-asset2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./builder/deepsea-patched.zip
          asset_name: deepsea-patched_v${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip



    - name: Upload Release Asset - DeepSea-Minimal
      id: upload-release-asset3
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./builder/deepsea-minimal.zip
          asset_name: deepsea-minimal_v${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip
